language: objective-c

osx_image: xcode10.2

env:
  matrix:
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone XR' CAN_DEPLOY=YES
    - TEST_SDK=iphonesimulator12.2 OS=10.0 NAME='iPhone 6s Plus'
    - TEST_SDK=iphonesimulator12.2 OS=10.0 NAME='iPhone 5s'

cache: cocoapods

podfile: Example/Podfile

before_install:
 - gem install xcpretty       
 - gem install cocoapods -v $(cat Example/Podfile.lock |grep COCOAPODS |awk '{print $2}')
 - pod install --project-directory=Example
  
script:
 - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/ECDHESSwift.xcworkspace -scheme ECDHESSwift-Example -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES | xcpretty
 - pod lib lint

after_success:
 - bash <(curl -s https://codecov.io/bash) -J 'ECDHESSwift'

deploy:
  provider: script
  script: ./scripts/pod_trunk_push.sh
  on:
    tags: true
    condition: $CAN_DEPLOY = YES
